### ISSUE TITLE
lib bug

### ISSUE THREAD

**Issue by yinde0** [benmack/eo-box#17] opened 2019-07-27 22:41 UTC
cannot import name 'convert_df_to_geodf'

**Comment by benmack** [comment] 2019-07-28 09:43
Thank you for reporting the bug. I very much appreciate it.
However, it would be great to have more information about the issue. What version of the package did you use and how did you import the function etc.
Therefore, please add some more information.

**Comment by yinde0** [comment] 2019-07-29 07:24
I tried cloning the github repo on colab and after I imported the directories and it poped up : cannot import name 'convert_df_to_geodf'.

**Comment by benmack** [comment] 2019-07-30 11:16
Can you please give me more information since I cannot easily reproduce your issue.

What version do you use? Please torun the following and report the version number that is returned.

```python
import eobox

eobox.__version__
```

If this already throws your error, please copy and paste here the code you used and the whole traceback message that is printed out.

Furthermore, if possible look into the package directory in the eobox/__init__.py file and see what version is written in there in the top line.

Else it is not easy to solve an issue that cannot be reproduced.

**Comment by benmack** [comment] 2020-06-05 20:50
Hi @yinde0 - sorry, I lost sight of this issue. It seems to be the same as the recently reportet #20. Could you please have a look if this solves your issue?

**Comment by benmack** [comment] 2020-06-11 08:59
I close this since I believe it is the same  issue as #20

**Closed as completed by benmack** 2020-06-11 08:59 UTC
